[tools]
bun = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "latest"

"npm:npkill" = "latest"
"npm:npm-check-updates" = "latest"
"npm:prettier" = "latest"
"npm:sort-package-json" = "latest"
"npm:vercel" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
