[tools]
python = "latest"
ruby = "latest"
rust = "latest"

"npm:npkill" = "latest"
"npm:prettier" = "latest"
"npm:sort-package-json" = "latest"
"npm:npm-check-updates" = "latest"

[tools.bun]
version = "latest"
postinstall = 'bun completions > "${HOME}/.zsh/completions/_bun"'

[tools.node]
version = "latest"
postinstall = 'npm completion > "${HOME}/.zsh/completions/_npm"'

[settings]
idiomatic_version_file_enable_tools = ["node"]
